vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+

"indent 4 spaces with tab and shift >
set tabstop=2
set shiftwidth=2
set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab

:syntax on

set nocompatible
set backspace=indent,eol,start

"remap redo
nnoremap r <C-R>

"remap direction keys in command mode

"down
"nnoremap k j
"up
"nnoremap i k

"right not edited
"nnoremap l l

"left
"nnoremap j h

"remap insert i to m 
"nnoremap m i

"automatic indent
set autoindent
"stop vim from removing indent from blank lines
inoremap <CR> <CR>x<BS>
nnoremap o ox<BS>
nnoremap O Ox<BS>

"add line numbers
:set number

"int at the same place of last line with enter
set autoindent
"set smartindent
:set paste

"vim /search highlight words
:set hlsearch

"remap end of line
"vnoremap q $
"nnoremap q $

"remap ESC to fd
vnoremap fd <ESC> 
vnoremap FD <ESC> 

"remap command mode
inoremap fd <Esc>
inoremap FD <Esc>

"noremap fd <ESC>
"noremap FD <ESC>

vnoremap fd <ESC> 
vnoremap FD <ESC> 

"cmap  fd <ESC>
"cmap  FD <ESC>

cnoremap fd <ESC>
cnoremap FD <ESC>
"cmap fd <ESC>
"cmap FD <ESC>

"cnoremap <C-j> <Down>
"cnoremap <C-k> <Up>

"inoremap <C-j> <Down>
"inoremap <C-k> <Up>

"inoremap ;; <ESC>ciw""<ESC>P
nnoremap ;; ciw""<ESC>P

